const theme = [
    { theme: "animaux"}, 
    { theme: "humour"}, 
    { theme: "amitié"}, 
    { theme: "autocollants"}, 
    { theme: "conte"}, 
    { theme: "activités"}, 
    { theme: "nature"}, 
    { theme: "aventure"}, 
    { theme: "comptines"}, 
    { theme: "amour"}, 
    { theme: "école"}, 
    { theme: "famille"}, 
    { theme: "histoire"}, 
    { theme: "Noël"}, 
    { theme: "enquête"}, 
    { theme: "loup"}, 
    { theme: "jeu"}, 
    { theme: "sport"}, 
    { theme: "éveil"}, 
    { theme: "quotidien"}, 
    { theme: "héros"}, 
    { theme: "vie quotidienne"}, 
    { theme: "monde"}, 
    { theme: "ruse"}, 
    { theme: "mer"}, 
    { theme: "dinosaures"}, 
    { theme: "magie"}, 
    { theme: "ferme"}, 
    { theme: "livre à toucher"},
    { theme: "sorcière"},
    { theme: "monstre"}, 
    { theme: "livre"},  
    { theme: "animé"},  
    { theme: "pirates"}, 
    { theme: "enfance"}, 
    { theme: "contes"}, 
    { theme: "peur"},  
    { theme: "voyage"}, 
    { theme: "sciences"},
    { theme: "transports"},
    { theme: "savane"},
    { theme: "questions d'enfant"},
    { theme: "documentaire"},
    { theme: "bêtises"},
    { theme: "langage"},
    { theme: "émotions"},
    { theme: "préhistoire"},
    { theme: "apprentissages"},
    { theme: "coloriages"},
    { theme: "chat"},
    { theme: "poésie"},
    { theme: "collège"},
    { theme: "différence"},
    { theme: "imagier"},
    { theme: "Afrique"},
    { theme: "France"},
    { theme: "art"},
    { theme: "mystères"},
    { theme: "imagerie"},
    { theme: "musique"},
    { theme: "vacances"},
    { theme: "forêt"},
    { theme: "conte de fées"},
    { theme: "espace"},
    { theme: "corps humain"},
    { theme: "Paris"},
    { theme: "journal intime"},
    { theme: "guerre"},
    { theme: "atlas"},
    { theme: "cuisine"},
    { theme: "géographie"},
    { theme: "alimentation"},
    { theme: "football"},
    { theme: "princesse"},
    { theme: "Moyen Âge"},
    { theme: "animaux sauvages"},
    { theme: "fêtes"},
    { theme: "fantastique"},
    { theme: "imagination"},
    { theme: "métiers"},
    { theme: "histoire de l'art"},
    { theme: "découverte"},
    { theme: "pompier"},
    { theme: "enfants"},
    { theme: "adolescence"},
    { theme: "imaginaire"},
    { theme: "père Noël"},
    { theme: "lecture"},
    { theme: "autonomie"},
    { theme: "Pâques"},
    { theme: "dragons"},
    { theme: "montagne"},
    { theme: "ville"},
    { theme: "petites bêtes"},
    { theme: "écologie"},
    { theme: "loisirs"},
    { theme: "insectes"},
    { theme: "éducation"},
    { theme: "princes et princesses"},
    { theme: "violence"},
    { theme: "ciel"},
    { theme: "peinture"},
    { theme: "nuit"},
    { theme: "chantier"},
    { theme: "frères et sœurs"},
    { theme: "courage"},
    { theme: "mythologie grecque"},
    { theme: "Terre"},
    { theme: "bande de copains"},
    { theme: "jeux"},
    { theme: "santé"},
    { theme: "animaux de compagnie"},
    { theme: "devinettes"},
    { theme: "château fort"},
    { theme: "chevaux"},
    { theme: "bricolage"},
    { theme: "chevalerie"},
    { theme: "grandir"},
    { theme: "cadeau"},
    { theme: "ours"},
    { theme: "engins"}, 
    { theme: "rêve"}, 
    { theme: "philosophie"}, 
    { theme: "poule"}, 
    { theme: "écriture"}, 
    { theme: "météo"}, 
    { theme: "chocolat"}, 
    { theme: "solidarité"}, 
    { theme: "soins"}, 
    { theme: "saisons"}, 
    { theme: "tendresse"}, 
    { theme: "bateau"}, 
    { theme: "chevaliers"}, 
    { theme: "interactivité"}, 
    { theme: "quête"}, 
    { theme: "filles"}, 
    { theme: "technologie"}, 
    { theme: "découverte du monde"}, 
    { theme: "animation"}, 
    { theme: "vivre ensemble"}, 
    { theme: "labyrinthe"}, 
    { theme: "maîtresse"}, 
    { theme: "ogre/ogresse"}, 
    { theme: "hiver"}, 
    { theme: "zoo"}, 
    { theme: "chiffres"}, 
    { theme: "combat"}, 
    { theme: "yoga"}, 
    { theme: "chansons"}, 
    { theme: "cirque"}, 
    { theme: "chiens"}, 
    { theme: "jeux de mots"}, 
    { theme: "danse"}, 
    { theme: "livre tissu"}, 
    { theme: "littérature"}, 
    { theme: "gâteaux"}, 
    { theme: "Fratrie"}, 
    { theme: "disparition"}, 
    { theme: "avions"}, 
    { theme: "poneys"}, 
    { theme: "maison"}, 
    { theme: "bébés animaux"}, 
    { theme: "plage"}, 
    { theme: "neige"}, 
    { theme: "environnement"}, 
    { theme: "copains"}, 
    { theme: "anatomie"}, 
    { theme: "banquise"}, 
    { theme: "instruments"}, 
    { theme: "conte détourné"}, 
    { theme: "identité"}, 
    { theme: "mondes imaginaires"}, 
    { theme: "partage"}, 
    { theme: "souris"}, 
    { theme: "arbre"}, 
    { theme: "astronomie"}, 
    { theme: "abécédaire"}, 
    { theme: "voitures"}, 
    { theme: "humanité"}, 
    { theme: "bain"}, 
    { theme: "culture"}, 
    { theme: "temps"}, 
    { theme: "animaux de la mer"}, 
    { theme: "couleurs"}, 
    { theme: "véhicules"}, 
    { theme: "sorcellerie"}, 
    { theme: "gourmandise"}, 
    { theme: "sortilège"}, 
    { theme: "anniversaire"}, 
    { theme: "Lune"}, 
    { theme: "construction"}, 
    { theme: "maman"}, 
    { theme: "humour décalé"}, 
    { theme: "prince"}, 
    { theme: "jardin"}, 
    { theme: "relations père-fils"}, 
    { theme: "adoption"}, 
    { theme: "bébé"}, 
    { theme: "jouets"}, 
    { theme: "parents"}, 
    { theme: "science-fiction"}, 
    { theme: "pop-up"}, 
    { theme: "recettes"}, 
    { theme: "toucher"}, 
    { theme: "camions"}, 
    { theme: "rébellion"}, 
    { theme: "vampire"}, 
    { theme: "Chaperon rouge"}, 
    { theme: "lumière"}, 
    { theme: "motricité"}, 
    { theme: "équitation"}, 
    { theme: "bonheur"}, 
    { theme: "moyens de transport"}, 
    { theme: "relaxation"}, 
    { theme: "jungle"}, 
    { theme: "Architecture"}, 
    { theme: "vengeance"}, 
    { theme: "volcan"}, 
    { theme: "ski"}, 
    { theme: "Antiquité"}, 
    { theme: "traditions"}, 
    { theme: "dent"}, 
    { theme: "observation"}, 
    { theme: "politesse"}, 
    { theme: "histoires"}, 
    { theme: "morale"}, 
    { theme: "rivalité"}, 
    { theme: "pouvoir"}, 
    { theme: "handicap"}, 
    { theme: "sentiments"}, 
    { theme: "classique"}, 
    { theme: "Réfléchir"}, 
    { theme: "sommeil"}, 
    { theme: "relations adulte/enfant"}, 
    { theme: "nourriture"}, 
    { theme: "coucher"}, 
    { theme: "champions"}, 
    { theme: "énigmes"}, 
    { theme: "animal de compagnie"}, 
    { theme: "train"}, 
    { theme: "liberté"}, 
    { theme: "Maternelle"}, 
    { theme: "jeu de cherche-et-trouve"}, 
    { theme: "maladie"}, 
    { theme: "judo"}, 
    { theme: "racisme"}, 
    { theme: "vêtements"}, 
    { theme: "plantes"}, 
    { theme: "mythologies"}, 
    { theme: "abandon"}, 
    { theme: "eau"}, 
    { theme: "sans-papiers"}, 
    { theme: "mémoire"}, 
    { theme: "Chine"}, 
    { theme: "fruits"}, 
    { theme: "voyage dans le temps"}, 
    { theme: "objets"}, 
    { theme: "fourmis"}, 
    { theme: "caprice"}, 
    { theme: "civilisations"}, 
    { theme: "pauvreté"}, 
    { theme: "cauchemar"}, 
    { theme: "créatures"}, 
    { theme: "grand-mère"}, 
    { theme: "princesses"}, 
    { theme: "sauvetage"}, 
    { theme: "bataille"}, 
    { theme: "sons"}, 
    { theme: "dieux et déesses"}, 
    { theme: "livre"}, 
    { theme: "récit initiatique"}, 
    { theme: "machines"}, 
    { theme: "préado"}, 
    { theme: "journée"}, 
    { theme: "jalousie"}, 
    { theme: "confiance"}, 
    { theme: "records"}, 
    { theme: "Grèce antique"}, 
    { theme: "humain"}, 
    { theme: "abeille"}, 
    { theme: "pollution"}, 
    { theme: "Formes"}, 
    { theme: "Araignée"}, 
    { theme: "propreté"}, 
    { theme: "Japon"}, 
    { theme: "défi"}, 
    { theme: "vélo"}, 
    { theme: "dauphin"}, 
    { theme: "policier"}, 
    { theme: "campagne"}, 
    { theme: "rire"}, 
    { theme: "livre pop-up"}, 
    { theme: "sports de glisse"}, 
    { theme: "travail"}, 
    { theme: "rugby"}, 
    { theme: "fantaisie"}, 
    { theme: "fée"}, 
    { theme: "Planètes"}, 
    { theme: "voyage initiatique"}, 
    { theme: "Séparation"}, 
    { theme: "manoir"}, 
    { theme: "pêche"}, 
    { theme: "immigration"}, 
    { theme: "cochon"}, 
    { theme: "encyclopédie"}, 
    { theme: "poissons"}, 
    { theme: "baleine"}, 
    { theme: "Coupe du monde"}, 
    { theme: "inventions"}, 
    { theme: "idées"}, 
    { theme: "lutins"}, 
    { theme: "planète"}, 
    { theme: "responsabilité"}, 
    { theme: "gros mots"}, 
    { theme: "sirènes"}, 
    { theme: "États-Unis"}, 
    { theme: "feu"}, 
    { theme: "économie"}, 
    { theme: "aliens"}, 
    { theme: "meurtre"}, 
    { theme: "puberté"}, 
    { theme: "entraide"}, 
    { theme: "Égypte"}, 
    { theme: "fugue"}, 
    { theme: "Rome"}, 
    { theme: "Contraires"}, 
    { theme: "gothique"}, 
    { theme: "dessin"}, 
    { theme: "région"}, 
    { theme: "dystopie"}, 
    { theme: "lapin"}, 
    { theme: "fantômes"}, 
    { theme: "médecin"}, 
    { theme: "poupée"}, 
    { theme: "tolérance"}, 
    { theme: "oiseaux"}, 
    { theme: "conte-randonnée"}, 
    { theme: "aliments"}, 
    { theme: "pâtisserie"}, 
    { theme: "catalogue"}, 
    { theme: "horreur"}, 
    { theme: "mission"}, 
    { theme: "absurde"}, 
    { theme: "chasse"}, 
    { theme: "fleurs"}, 
    { theme: "chasse au trésor"}, 
    { theme: "méchanceté"}, 
    { theme: "génie"}, 
    { theme: "féminisme"}, 
    { theme: "pardon"}, 
    { theme: "corps"}, 
    { theme: "mort"}, 
    { theme: "politique"}, 
    { theme: "mensonges"}, 
    { theme: "amis"}, 
    { theme: "voyage intergalactique"}, 
    { theme: "matières"}, 
    { theme: "dormir"}, 
    { theme: "secret"}, 
    { theme: "Bretagne"}, 
    { theme: "doudou"}, 
    { theme: "piscine"}, 
    { theme: "légende"}, 
    { theme: "Internet"}, 
    { theme: "légumes"}, 
    { theme: "découvertes"}, 
    { theme: "natation"}, 
    { theme: "renard"}, 
    { theme: "confiance en soi"}, 
    { theme: "illusions"}, 
    { theme: "Europe"}, 
    { theme: "souvenirs"}, 
    { theme: "mariage"}, 
    { theme: "Climat"}, 
    { theme: "informatique"}, 
    { theme: "pays"}, 
    { theme: "étoiles"}, 
    { theme: "souhait"}, 
    { theme: "justice"}, 
    { theme: "peur du noir"}, 
    { theme: "grand-père"}, 
    { theme: "petite enfance"}, 
    { theme: "traque"}, 
    { theme: "pipi"}, 
    { theme: "paysages"}, 
    { theme: "robot"}, 
    { theme: "religion"}, 
    { theme: "Rome antique"}, 
    { theme: "super-héros"}, 
    { theme: "bal"}, 
    { theme: "rencontre"}, 
    { theme: "parodie"}, 
    { theme: "hôpital"}, 
    { theme: "naissance"}, 
    { theme: "médiéval fantastique"}, 
    { theme: "mode"}, 
    { theme: "diversité"}, 
    { theme: "secrets"}, 
    { theme: "trahison"}, 
    { theme: "Jeux olympiques"}, 
    { theme: "moulin"}, 
    { theme: "expériences"}, 
    { theme: "assassinat"}, 
    { theme: "famille recomposée"}, 
    { theme: "langue française"}, 
    { theme: "reines"}, 
    { theme: "Toilette"}, 
    { theme: "élevage"}, 
    { theme: "tableaux"}, 
    { theme: "mime"}, 
    { theme: "Léonard de Vinci"}, 
    { theme: "réalité virtuelle"}, 
    { theme: "zombies"}, 
    { theme: "école primaire"}, 
    { theme: "Angleterre"}, 
    { theme: "solitude"}, 
    { theme: "Désobéissance"}, 
    { theme: "cheveux"}, 
    { theme: "prison"}, 
    { theme: "tribus"}, 
    { theme: "Égypte ancienne"}, 
    { theme: "école de magie"}, 
    { theme: "lait"}, 
    { theme: "illusions d'optique"}, 
    { theme: "fête foraine"}, 
    { theme: "compétition"}, 
    { theme: "livre-CD"}, 
    { theme: "BD"}, 
    { theme: "vétérinaire"}, 
    { theme: "lion"}, 
    { theme: "Respect"}, 
    { theme: "sœur"}, 
    { theme: "Crocodile"}, 
    { theme: "sapin"}, 
    { theme: "célébrité"}, 
    { theme: "tennis"}, 
    { theme: "relation frère/sœur"}, 
    { theme: "poney-club"}, 
    { theme: "anglais"}, 
    { theme: "Égypte antique"}, 
    { theme: "conquête spatiale"}, 
    { theme: "quête d'identité"}, 
    { theme: "scolarité"}, 
    { theme: "rentrée des classes"}, 
    { theme: "monuments"}, 
    { theme: "danse classique"}, 
    { theme: "trésor"}, 
    { theme: "mots"}, 
    { theme: "Crèche"}, 
    { theme: "argent"}, 
    { theme: "filles/garçons"}, 
    { theme: "exil"}, 
    { theme: "Far West"}, 
    { theme: "clonage"}, 
    { theme: "clown"}, 
    { theme: "patience"}, 
    { theme: "inégalités"}, 
    { theme: "Halloween"}, 
    { theme: "code de la route"}, 
    { theme: "peuples"}, 
    { theme: "jardinage"}, 
    { theme: "Ruche"}, 
    { theme: "Malice"}, 
    { theme: "Versailles"}, 
    { theme: "pot"}, 
    { theme: "insolite"}, 
    { theme: "lutte du bien contre le mal"}, 
    { theme: "Amérique"}, 
    { theme: "société"}, 
    { theme: "sculpture"}, 
    { theme: "alphabet"}, 
    { theme: "héroïsme"}, 
    { theme: "préjugés"}, 
    { theme: "créatures maléfiques"}, 
    { theme: "surdité"}, 
    { theme: "règles"}, 
    { theme: "thriller"}, 
    { theme: "aimants"}, 
    { theme: "bobos"}, 
    { theme: "grands-parents"}, 
    { theme: "questions intimes"}, 
    { theme: "exclusion"}, 
    { theme: "divorce"}, 
    { theme: "ingéniosité"}, 
    { theme: "découverte de soi"}, 
    { theme: "communication"}, 
    { theme: "Kirikou"}, 
    { theme: "espionnage"}, 
    { theme: "colère"}, 
    { theme: "savants"}, 
    { theme: "moto"}, 
    { theme: "ombre"}, 
    { theme: "copines"}, 
    { theme: "papa"}, 
    { theme: "démocratie"}, 
    { theme: "île paradisiaque"}, 
    { theme: "ourson"}, 
    { theme: "sports d'hiver"}, 
    { theme: "dragon"}, 
    { theme: "pompiers"}, 
    { theme: "blagues"}, 
    { theme: "Indiens"}, 
    { theme: "comportements animaux"}, 
    { theme: "New York"}, 
    { theme: "loisirs créatifs"}, 
    { theme: "Esclavage"}, 
    { theme: "Renaissance"}, 
    { theme: "timidité"}, 
    { theme: "Paix"}, 
    { theme: "absence"}, 
    { theme: "ours en peluche"}, 
    { theme: "président de la République"}, 
    { theme: "graphisme"}, 
    { theme: "suspense"}, 
    { theme: "s'habiller"}, 
    { theme: "Pompéi"}, 
    { theme: "roi"}, 
    { theme: "poursuite"}, 
    { theme: "Univers"}, 
    { theme: "images"}, 
    { theme: "Apocalypse"}, 
    { theme: "poids"}, 
    { theme: "dispute"}, 
    { theme: "héroïne"}, 
    { theme: "vieillesse"}, 
    { theme: "véhicules de secours"}, 
    { theme: "livre-puzzle"}, 
    { theme: "Orient"}, 
    { theme: "folie"}, 
    { theme: "animaux et leurs petits"}, 
    { theme: "Vol"}, 
    { theme: "repas"}, 
    { theme: "deuil"}, 
    { theme: "badminton"}, 
    { theme: "numérique"}, 
    { theme: "crottes"}, 
    { theme: "détente"}, 
    { theme: "camping"}, 
    { theme: "questionnement"}, 
    { theme: "cinéma"}, 
    { theme: "connaissance"}, 
    { theme: "Sagesse"}, 
    { theme: "droits des enfants"}, 
    { theme: "câlin"}, 
    { theme: "grossesse"}, 
    { theme: "nouvelles technologies"}, 
    { theme: "métamorphose"}, 
    { theme: "recyclage"}, 
    { theme: "cuisine du monde"}, 
    { theme: "boulangerie"}, 
    { theme: "harcèlement"}, 
    { theme: "dictionnaire visuel"}, 
    { theme: "outils"}, 
    { theme: "Provence"}, 
    { theme: "monstres"}, 
    { theme: "deux-roues"}, 
    { theme: "homosexualité"}, 
    { theme: "pôles"}, 
    { theme: "sexualité"}, 
    { theme: "zombis"}, 
    { theme: "père"}, 
    { theme: "histoire d'amour"}, 
    { theme: "phénomène étrange"}, 
    { theme: "viol"}, 
    { theme: "humeur"}, 
    { theme: "musiques"}, 
    { theme: "robotique"}, 
    { theme: "recettes internationales"}, 
    { theme: "pain"}, 
    { theme: "Fables"}, 
    { theme: "psychanalyse"}, 
    { theme: "chansons traditionnelles"}, 
    { theme: "sport de raquettes"}, 
    { theme: "décisions"}, 
    { theme: "photographie"}, 
    { theme: "amoureux"}, 
    { theme: "autorité parentale"}, 
    { theme: "lapin nain"}, 
    { theme: "personnalités"}, 
    { theme: "s'amuser dehors"}, 
    { theme: "histoire du monde"}, 
    { theme: "chronologie"}, 
    { theme: "pâtisseries"}, 
    { theme: "Vikings"}, 
    { theme: "femme"}, 
    { theme: "amnésie"}, 
    { theme: "ados"}, 
    { theme: "autorité"}, 
    { theme: "petit frère/petite sœur"}, 
    { theme: "Corse"}, 
    { theme: "ballons"}, 
    { theme: "exploration"}, 
    { theme: "poils"}, 
    { theme: "Freestyle"}, 
    { theme: "livre-cadeau Jeunesse"}, 
    { theme: "Blanche-Neige"}, 
    { theme: "paléontologie"}, 
    { theme: "presse"}, 
    { theme: "coccinelle"}, 
    { theme: "Odyssée"}, 
    { theme: "télévision"}, 
    { theme: "réseaux sociaux"}, 
    { theme: "orphelinat"}, 
    { theme: "chocolatindépendance"}, 
    { theme: "librairie"}, 
    { theme: "drakkar"}, 
    { theme: "expédition"}, 
    { theme: "sociopathe"}, 
    { theme: "garçons"}, 
    { theme: "évolution de l'espèce humaine"}, 
    { theme: "grand frère/grande sœur"}, 
    { theme: "créativité"}, 
    { theme: "enquête policière"}, 
    { theme: "relations père-fille"}, 
    { theme: "Archéologie"}, 
    { theme: "Séduction"}, 
    { theme: "camp d'été"}, 
    { theme: "abécédaireabécédaire"}, 
    { theme: "jeune fille"}, 
    { theme: "phase d'opposition"}, 
    { theme: "biodiversité"}, 
    { theme: "Berlin"}, 
    { theme: "hip-hop"}, 
    { theme: "découverte scientifique"}, 
    { theme: "Erasmus"}, 
    { theme: "dénombrer"}, 
    { theme: "ballon ovale"}, 
    { theme: "oubli"}, 
    { theme: "relations prof/élèves"}, 
    { theme: "anticonformisme"}, 
    { theme: "Microscope"}, 
    { theme: "vanité"}, 
    { theme: "Napoléon"}, 
    { theme: "électricité"}, 
    { theme: "garde alternée"}, 
    { theme: "création"}, 
    { theme: "psychologie"}, 
    { theme: "colère/joie/tristesse/peur/amour..."}, 
    { theme: "petite souris"}, 
    { theme: "vache"}, 
    { theme: "lycée"}, 
    { theme: "numération"}, 
    { theme: "sport collectif"}, 
    { theme: "heroic fantasy"}, 
    { theme: "carnaval"}, 
    { theme: "déménagement"}, 
    { theme: "développement durable"}, 
    { theme: "relations fille/garçon"}, 
    { theme: "Cerf"}, 
    { theme: "prénom"}, 
    { theme: "Orphelin"}, 
    { theme: "Alice"}, 
    { theme: "flatterie"}, 
    { theme: "soleil"}, 
    { theme: "jeunesse"}, 
    { theme: "amour toxique"}, 
    { theme: "amour filial"}, 
    { theme: "Picasso"}, 
    { theme: "chats"}, 
    { theme: "transgenre"}, 
    { theme: "rangement"}, 
    { theme: "autisme"}, 
    { theme: "pré"}, 
    { theme: "intolérance"}, 
    { theme: "quantité"}, 
    { theme: "bien-être"}, 
    { theme: "farces"}, 
    { theme: "Fabrication"}, 
    { theme: "athlétisme"}, 
    { theme: "Nazisme"}, 
    { theme: "Calcul"}, 
    { theme: "Beauté"}, 
    { theme: "Révolution française"}, 
    { theme: "écrans"}, 
    { theme: "questions"}, 
    { theme: "Lyon"}, 
    { theme: "impressionnisme"}, 
    { theme: "droits civiques"}, 
    { theme: "pyramides"}, 
    { theme: "Pays basque"}, 
    { theme: "complot"}, 
    { theme: "arts plastiques"}, 
    { theme: "migrants"}, 
    { theme: "jeu vidéo"}, 
    { theme: "chance"}, 
    { theme: "Onomatopées"}, 
    { theme: "feuilles"}, 
    { theme: "délinquance"}, 
    { theme: "douceurs sucrées"}, 
    { theme: "désert"}, 
    { theme: "Mozart"}, 
    { theme: "société secrète"}, 
    { theme: "parc d'attractions"}, 
    { theme: "malédiction"}, 
    { theme: "Van Gogh"}, 
    { theme: "apparence"}, 
    { theme: "pharaons"}, 
    { theme: "sécurité routière"}, 
    { theme: "Pyrénées"}, 
    { theme: "classe verte"}, 
    { theme: "égalité filles-garçons"}, 
    { theme: "réfugiés"}, 
    { theme: "polar"}, 
    { theme: "bombe atomique"}, 
    { theme: "malchance"}, 
    { theme: "Espagne"}, 
    { theme: "papillons"}, 
    { theme: "herbier"}, 
    { theme: "rois de France"}, 
    { theme: "milieu"}, 
    { theme: "pâtissier"}, 
    { theme: "gymnastique"}, 
    { theme: "ordinateur"}, 
    { theme: "tournage d'un film"}, 
    { theme: "pâte à modeler"}, 
    { theme: "double vie"}, 
    { theme: "biographie"}, 
    { theme: "taupe"}, 
    { theme: "injustice"}, 
    { theme: "voiture"}, 
    { theme: "école maternelle"}, 
    { theme: "précocité intellectuelle"}, 
    { theme: "grenouille"}, 
    { theme: "étudiants"}, 
    { theme: "Glisse"}, 
    { theme: "réflexion"}, 
    { theme: "autrui"}, 
    { theme: "pieds"}, 
    { theme: "coiffeur"}, 
    { theme: "basketball"}, 
    { theme: "Champignon"}, 
    { theme: "fiction"}, 
    { theme: "bagarre"}, 
    { theme: "terrorisme"}, 
    { theme: "cabane"}, 
    { theme: "œufs"}, 
    { theme: "vérité"}, 
    { theme: "difficulté en classe"}, 
    { theme: "trolls"}, 
    { theme: "jeux d'observation"}, 
    { theme: "relations mère-fille"}, 
    { theme: "disputes et jalousies"}, 
    { theme: "relation au pouvoir et à l'autorité"}, 
    { theme: "négativité"}, 
    { theme: "Devoirs"}, 
    { theme: "croissance"}, 
    { theme: "tristesse"}, 
    { theme: "vie dans la rue"}, 
    { theme: "argent de poche"}, 
    { theme: "pieuvre"}, 
    { theme: "skate"}, 
    { theme: "catastrophes naturelles"}, 
    { theme: "accomplissement de soi"}, 
    { theme: "abstraction"}, 
    { theme: "carotte"}, 
    { theme: "éléphant"}, 
    { theme: "pomme"}, 
    { theme: "Rodin"}, 
    { theme: "goûters"}, 
    { theme: "suicide"}, 
    { theme: "spectacle"}, 
    { theme: "bien et mal"}, 
    { theme: "sorties"}, 
    { theme: "expression"}, 
    { theme: "obscurité"}, 
    { theme: "vocabulaire"}, 
    { theme: "tracteurs"}, 
    { theme: "Table ronde"}, 
    { theme: "tétine"}, 
    { theme: "différences"}, 
    { theme: "fraternité"}, 
    { theme: "chaussures"}, 
    { theme: "Marseille"}, 
    { theme: "éléphants"}, 
    { theme: "verger"}, 
    { theme: "Klimt"}, 
    { theme: "escargot"}, 
    { theme: "attente"}, 
    { theme: "cochon d'Inde"}, 
    { theme: "hamster"}, 
    { theme: "actualité"}, 
    { theme: "Normandie"}, 
    { theme: "western"}, 
    { theme: "théâtre"}, 
    { theme: "garderie"}, 
    { theme: "matériel"}, 
    { theme: "noir"}, 
    { theme: "transidentité"}, 
    { theme: "mathématiques"}, 
    { theme: "information"}, 
    { theme: "histoire de France"}, 
    { theme: "combat entre les forces du bien et du mal"}, 
    { theme: "vie de famille chez  animaux"}, 
    { theme: "comptage"}, 
    { theme: "relations mère/enfant"}, 
    { theme: "voisinage"}, 
    { theme: "moqueries"}, 
    { theme: "rois et souverains"}, 
    { theme: "médecine"}, 
    { theme: "complicité entre grands-parents et petits-enfants"}, 
    { theme: "cachette"}, 
    { theme: "morsure"}, 
    { theme: "complicité"}, 
    { theme: "fille"}, 
    { theme: "agent secret"}, 
    { theme: "sport féminin"}, 
    { theme: "usage"}, 
    { theme: "désinformation"}, 
    { theme: "comparaisons"}, 
    { theme: "éthologie"}, 
    { theme: "Parole"}, 
    { theme: "rumeurs"}, 
    { theme: "géant"}, 
    { theme: "premières découvertes"}, 
    { theme: "accident"}, 
    { theme: "zizi"}, 
    { theme: "royaume"}, 
    { theme: "drapeaux"}, 
    { theme: "caserne"}, 
    { theme: "hasard"}, 
    { theme: "voile"}, 
    { theme: "danger"}, 
    { theme: "journalistes"}, 
    { theme: "VIH"},
    { theme: "érotique"},
    { theme: "destruction"}
];

const options = theme.map(option => {
    const firstLetter = option.theme[0].toUpperCase();
    return {
      firstLetter: /[0-9]/.test(firstLetter) ? '0-9' : firstLetter,
      ...option,
    };
  });

export default options;